# Generated by Django 3.1.7 on 2021-05-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='added_date',
        ),
    ]
