# Generated by Django 3.1.7 on 2021-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todolist', '0005_auto_20210504_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'Completed'), (2, 'TO be done')], default='pending', max_length=250, null=True),
        ),
    ]
