# Generated by Django 3.1.7 on 2021-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todolist', '0006_auto_20210504_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'completed'), (2, 'pending')], default='pending', max_length=250, null=True),
        ),
    ]
